CSV_PATH = "data/forbes_billionaires_simulation_minimal_v3.csv"
EDGE_CSV_PATH = "data/forbes_billionaires_edges.csv"

OUTPUT_DIR = "output"

# CSV columns expected by the loader:
# ID, Name, NetWorth_Billions, x, y, z, vx, vy, vz

# For quick testing, use 100 or 200.
# For a larger final run, increase this to 1000 or None.
MAX_PARTICLES = 100

# Initial velocity settings
# The current version uses connection-based velocity vectors.
# vx, vy, vz are generated by scripts/generate_connection_velocity.py
# and then read directly by src/data_loader.py.
#
# Keep this as 1.0 because the velocity is already scaled during preprocessing.
INITIAL_VELOCITY_SCALE = 1.0

# Physics settings
G = 0.005
DT = 0.02
STEPS = 3000
SOFTENING = 2.0
SAVE_EVERY = 3

# Export settings
SAVE_GIF = True
SAVE_VVVV_CSV = True
SAVE_EDGE_CSV = True

# Output file names
OUTPUT_GIF_NAME = "billionaires_nbody_3d.gif"
OUTPUT_VVVV_CSV_NAME = "billionaires_nbody_for_vvvv.csv"
OUTPUT_EDGE_CSV_NAME = "billionaires_edges_for_vvvv.csv"

# Animation settings
FPS = 30
INTERVAL_MS = 30
DPI = 120

# Display settings
POINT_MIN_SIZE = 10
POINT_MAX_EXTRA_SIZE = 200
CAMERA_ELEVATION = 25
CAMERA_AZIMUTH = 45
CAMERA_ROTATION_SPEED = 0.0